CXX=/opt/lgp/base/i386/bin/i386-linux-c++
#LD=/opt/lgp/base/i386/bin/i386-linux-ld
CORONA_CFLAGS=-I/tmp/corona/include
CORONA_LIBS=-L/tmp/corona/lib
X11_LIBS=-L/opt/lgp/base/i386/i386-linux/usr/X11R6/lib -lX11
