rmdir /S /Q CVS
rmdir /S /Q bin\CVS
rmdir /S /Q boundscheck\CVS
rmdir /S /Q doc\CVS
rmdir /S /Q lua\CVS
rmdir /S /Q lua\include\CVS
rmdir /S /Q lua\src\CVS
rmdir /S /Q lua\src\lib\CVS
rmdir /S /Q gtk\CVS
rmdir /S /Q scripts\CVS
rmdir /S /Q src\CVS
rmdir /S /Q vcbuild\CVS
rmdir /S /Q win32\CVS
del /S /Q .cvsignore
